services:

  neo4j:
    image: neo4j:5.26-community
    container_name: KnowledgeGraph
    restart: on-failure:3
    environment:
      - NEO4J_AUTH=none
    networks:
      - dev
    ports:
      - target: 7474
        host_ip: 127.0.0.1
        published: 7474
        protocol: tcp
        mode: host
      - target: 7687
        host_ip: 127.0.0.1
        published: 7687
        protocol: tcp
        mode: host
    volumes:
      - /volume1/docker/neo4j/data:/neo4jdata

volumes:
  neo4jdb:

networks:
    dev: